databases:
  - name: start_db
    databaseName: start_db
    user: start_db

services:
  - type: web
    name: start_db
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: start_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false